#!/usr/bin/env python3
"""Merge two teacher-generated JSONLs into an MT-SeqKD training set.

Paper §5.1 specifies a 7:3 strong-to-weak teacher mix for MT-SeqKD.  Each
input file is assumed to be a JSONL of messages-format rows where the last
assistant turn was generated by the corresponding teacher (offline).

Usage:
    python data/prepare_mt_seqkd.py \\
        --teacher1_jsonl ./data_cache/seqkd/teacher1.jsonl \\
        --teacher2_jsonl ./data_cache/seqkd/teacher2.jsonl \\
        --ratio 0.7 \\
        --out ./data_cache/seqkd/merged.jsonl
"""
import argparse
import json
import random
from pathlib import Path


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--teacher1_jsonl', required=True,
                        help='Responses from the stronger teacher.')
    parser.add_argument('--teacher2_jsonl', required=True,
                        help='Responses from the weaker teacher.')
    parser.add_argument('--ratio', type=float, default=0.7,
                        help='Fraction of final samples drawn from teacher-1.')
    parser.add_argument('--seed', type=int, default=42)
    parser.add_argument('--out', required=True, help='Output JSONL path.')
    args = parser.parse_args()

    rng = random.Random(args.seed)

    def load(p):
        with open(p) as f:
            return [json.loads(l) for l in f if l.strip()]

    t1 = load(args.teacher1_jsonl)
    t2 = load(args.teacher2_jsonl)

    n = min(len(t1), len(t2))
    n_t1 = int(n * args.ratio)
    n_t2 = n - n_t1

    merged = rng.sample(t1, n_t1) + rng.sample(t2, n_t2)
    rng.shuffle(merged)

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open('w') as f:
        for row in merged:
            f.write(json.dumps(row, ensure_ascii=False) + '\n')

    print(f'Wrote {len(merged)} samples ({n_t1} from T1 / {n_t2} from T2) -> {out}')


if __name__ == '__main__':
    main()
